sudo: false
language: scala
jdk: openjdk11

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: docs-update
    if: (branch = master) AND NOT fork

scala_version_212: &scala_version_212 "2.12.10"

jobs:
  include:
    # stage="test" if no stage is specified
    - name: test 2.12
      scala: *scala_version_212
      script: 
        - sbt ++$TRAVIS_SCALA_VERSION ci
      after_success:
        - bash <(curl -s https://codecov.io/bash)  
    - stage: docs-update
      name: microsite
      scala: *scala_version_212
      script:
        sbt ++$TRAVIS_SCALA_VERSION docs/docusaurusPublishGhpages

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - $HOME/.cache
    - $HOME/.sbt
