version: '3'
services:

  service:
    restart: always
    image: "http-service:latest"
    environment:
      APPLICATION_HTTP_HOST: "0.0.0.0"
      APPLICATION_HTTP_PORT: 9000
      LOG_LEVEL: "INFO"
      POSTGRESQL_URI: "jdbc:postgresql://postgres:5432/http-service"
      POSTGRESQL_USER: "postgres"
      POSTGRESQL_PASSWORD: "admin"
    ports:
      - 9000:9000
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: http-service
    ports:
      - 55432:5432
