version: '3'
services:

  postgres:
    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: http4s-tagless-example
    ports:
      - 55432:5432

networks:
  default:
    external:
      name: ${NETWORK}
